### PR TITLE
Fix parsing multiple nested generics

### PR DESCRIPTION
**Pull request by TypeSafeSchwalbe**
When generics such as `A<B<C>>` are parsed, the `>>` would previously lead to problems when parsing. This has been fixed.

### CODE REVIEW

**Comment by TypeSafeSchwalbe** [comment]
@mauro-balades you should first make the changes to your local copy of Snowball and see if they actually work

**Review by mauro-balades — COMMENTED** [review]
good 👍🏽

**Comment by mauro-balades** [comment]
@TypeSafeSchwalbe It still doesn't work with `parseGenericExpr` and I need to go. If you could do it great, if not, I will test it later. 👍🏽 

```
[error]: (Syntax error) Expected '(' but got '>>'
╚══╤══╝
   ╰───╮
       ├─[/home/mauro/work/snowball/tests/tuples.sn:50:45]
       │
    48 │  @test(expect = 2) 
    49 │  public func pair_with_vector2() i32 {
    50 >      let x = new Tuples::Pair<i32, Vector<i32>>(1, new Vector<?i32>());
       │                                              ~~ 
    51 │      x.second.push_back(1);
    52 │      return x.first + x.second.size();
       │
   ────╯
```

**Comment by mauro-balades** [comment]
don't close it

**Pull request closed without merging**
