### PR TITLE
Re-Calculating power to Static Constant 

### PR DESCRIPTION
**Pull request by y9rabbito**
This is regarding the issue #103, modify the re-calculating power to constant static variable.

### CODE REVIEW

**Comment by mauro-balades** [comment]
I wonder why the `4294967296`?

**Comment by y9rabbito** [comment]
@mauro-balades and other maintainers could you please take your time and check it if it's alright and can be merged or not.

**Comment by y9rabbito** [comment]
> I wonder why the `4294967296`?

Cause pow(2,32) evaluates to this value.

**Comment by mauro-balades** [comment]
Copilot playing games with me again 😔

**Comment by y9rabbito** [comment]
> Copilot playing games with me again 😔

Thank you sir!

**Pull request merged**
